spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_veritabani
spring.datasource.username=postgres
spring.datasource.password=mami1903-
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=change-this-secret-key-to-32-plus-chars
app.jwt.expiration-hours=24
